name = "woobot-landingpage"
compatibility_date = "2024-12-31"
main = "./.opennext/worker.js"
assets = { directory = "./.opennext/assets" }

[build]
command = "npm run opennext:build"

[[routers]]
rule = "/*"
module = "./.opennext/router.mjs"

[site]
bucket = "./.opennext/assets"

# Optional: Add environment variables
[vars]
NODE_ENV = "production"